### ISSUE TITLE
Help text - typos

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/brc-ds-eval#8]
1. Under Loading your data section
Not all of these fields have to be mapped - it depends on which of the available tools you wish to use and, in some cases, **now** you want to use the tool. See the section on each tool to see which fields must be mapped.

Now should how?

2. Under section - The Time Series tool
The Time series tool displays at thumbnail bar chart.

should be 'a' not 'at'?

3. Under section - The Time Series tool
The Display dataset controls allow you show charts.

should be ...allows you to show charts...

4. Under section - The time Series tool
on a some text 

should be '...on some text...'

5. Under the 'Explore map tool'
typo = cluster of recrds

**Comment by burkmarr** [comment]
Actioned.
